### ISSUE TITLE
why does ScanNeo realign with bwa?

### ISSUE THREAD

**Issue by indapa** [ylab-hi/ScanNeo#1]
Really interesting [paper](https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btz193/5384488) and tool. I'm wondering why reads are converted to single end and then realigned with bwa, as described in the publication?

> Retained reads were converted to single-end reads in FASTQ file using BEDTools (Quinlan and Hall, 2010) and re-aligned using BWA-MEM (Li, 2013) which reports chimeric alignments with an ‘SA’ tag in the alignment records. Finally, ScanNeo applied transIndel (Yang et al., 2018) to determine small to large-sized indels from the RNA-Seq reads. Indel calls were reported in variant call format (VCF) file.

**Comment by dolittle007** [comment]
Because in the previous step, we removed spliced reads with inferred transcriptional directions but not carrying indels within their alignment. it made paired-end reads mapping impossible. Additionally, transIndel need chimeric alignments from BWA-MEM to infer small to large-sized Indels. Thus, BWA-MEM was applied to single-end reads mapping.
